apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-rage-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-rage-gitops
    spec:
      serviceAccountName: rage-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=rage-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/rage-notebook -- git clone https://github.com/jrichter-rhtap/rage123
      restartPolicy: Never
